import ProjectDescription

let workspace = Workspace(
  name: "DarrarskiApp",
  projects: [
    "./Projects/App",
    "./Projects/AppIcon",
    "./Projects/Tools",
  ],
  additionalFiles: [
    "./README.md",
    "./LICENSE",
    .folderReference(path: .relativeToRoot("web")),
  ],
  generationOptions: .options(
    enableAutomaticXcodeSchemes: true,
    autogeneratedWorkspaceSchemes: .enabled(
      codeCoverageMode: .relevant,
      testingOptions: [.parallelizable, .randomExecutionOrdering]
    ),
    lastXcodeUpgradeCheck: Version("15.4")
  )
)
